### ISSUE TITLE
Installer has malware

### ISSUE THREAD

**Issue by GeeDeexd** [bennykor/Axon7Toolkit#1]
The installer has malware, you should get a malware free installer.

**Comment by bennykor** [comment]
@GeeDeexd

It does not, it is a false positive. I used Inno Setup which definitely does not have it.

**Comment by bennykor** [comment]
The problem is not the installer it is the program itself. For some reason any batch file that I compile, even a blank one, gets confused for malware. I'm looking for a different compiler but I paid $50 a year for the one I use now :(
